service: python-s3-thumbnail

# set global vars
provider:
  name: aws
  runtime: python2.7
  region: us-east-1
  profile: serverless-admin
  timeout: 10
  memorySize: 128
  # allow func to do anything on s3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: 'arn:aws:s3:::allens-image-bucket/*'
  # set def values of env vars
  environment:
    THUMBNAIL_SIZE: '128'

custom:
  bucket: allens-image-bucket
  pythonRequirements:
    dockerizePip: true

functions:
  s3-thumbnail-generator:
    # path to handler function
    handler: handler.s3_thumbnail_generator
    # trigger handler when .png added to our bucket
    events:
      - s3:
        bucket: ${self:custom.bucket}
        event: s3:ObjectCreated:*
        rules:
          - suffix: .png

# bundle dependencies from requiremeents.txt with function
plugins:
  - serverless-python-requirements
